### ISSUE TITLE
Failed to compile in NextJS

### ISSUE THREAD

**Issue by soonki-98** [ssi02014/react-thumbnail-generator#3]
while using your package with NextJS project, the error below occurred.
<img width="974" alt="image" src="https://user-images.githubusercontent.com/63432381/220224331-210bd161-df04-40e2-a7ae-9dcb1e166995.png">

According to "Read more", 
One of your dependencies (`node_modules`) imports a CSS file.
This normally happens when a package's source files are accidentally consumed, instead of the built package.

**Comment by ssi02014** [comment]
해결되서 close합니다
